language: c

sudo: required
dist: trusty

env:
  global:
    - GH_REF: github.com/DanNixon/ArduinoUniversalInput.git
    - secure: "UmT3pNi1KOd79Lr32LxsmA4E2vhs65ateBkQEe17MwlEqIV0EUnPbWbvdrwZw7USFQDSuOvhHFMw0hOU5nJ03dK9OiALZUO82yaOa2yFDkFqtAfltocQyHkCGmz4K9k5XDjqPRWfw6KD8sxkvUFmz9ddC48GxhHfmqyowdW5Xwk="

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y doxygen graphviz
  - source <(curl -SLs https://raw.githubusercontent.com/adafruit/travis-ci-arduino/master/install.sh)

install:
  - arduino --install-library "Adafruit MCP23017 Arduino Library"

script:
  - build_platform uno
  - build_platform leonardo
  - build_platform arduino:avr:mega
  - build_platform esp8266
  - doxygen
  - ./.travis_deploy_docs.sh

notifications:
  email:
    on_success: change
    on_failure: change
