language: cpp

install:
  - sudo apt-get update
  - sudo apt-get install -y arduino python-pip
  - sudo pip install ino

script:
  - ./.generate_and_build.sh UniversalInputs/examples/ArduinoButtonBasic
  - ./.generate_and_build.sh UniversalInputs/examples/ArduinoMatrixButtonBasic
  - ./.generate_and_build.sh UniversalInputs/examples/UniversalInputManager

os:
  - linux
